### ISSUE TITLE
[Segurança]: Permitir ataque de força bruta e outros ataques automatizados

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#111]
-Com um número muito grande de tentativas de acesso, isso pode sobrecarregar o servidor, fazendo ele ficar fora do ar

Possível solução:
Manter um log de todas as falhas de login e aumentar o delay após falhas de login e impor um limite de tentativas de login falhas sucessivas, com bloqueio temporário da conta

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Resolvido através do google OAuth.
![image](https://user-images.githubusercontent.com/61878987/103487807-ca7df000-4de6-11eb-9353-d45ca6a013fc.png)
