### ISSUE TITLE
[Segurança]: IDs de sessões na URL, repetidos ou não invalidados

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#115]
-Permite que usuários maliciosos guardem os IDs de sessões de usuários e então acessem seus dados

Possível solução:
Implementação de gerenciador de sessão no lado do servidor, que gere um ID de sessão aleatório, de alta entropia, salvo de forma segura em separado dos outros dados, não expostos na URL e que são invalidados depois de logout, ociosidade por um tempo determinado ou timeout.

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Como dito na #118, os ID de sessões são criptografados e também renovados em caso de login com sucesso.
Os IDs de sessões são armazenados em cookies e não na URL como mostrado na #118.
