### ISSUE TITLE
[Segurança]: Rotatividade de chaves de criptografia e uso de chaves fortes

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#118]
Possível solução:
Uso de padrões de chaves fortes e sistema de rotação de chaves

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
As chaves são os IDs de sessão criptografados. O processo de criptografia fica a cargo do [passportjs](http://www.passportjs.org/).
![image](https://user-images.githubusercontent.com/61878987/103487438-432f7d00-4de4-11eb-80da-cea54e1cee7b.png)
