### ISSUE TITLE
[Segurança]: Não há criptografia sendo usada no código

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#119]
Possível solução:
Uso de ferramentas de hash fortemente adaptativo como Argon2 e scrypt para salvar senhas

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Aplicação não armazena senhas pois a autenticação é feita através do google OAuth.
![image](https://user-images.githubusercontent.com/61878987/103487388-c69c9e80-4de3-11eb-9e4e-b006bf79b38a.png)
