### ISSUE TITLE
[Segurança]: Não há verificação de login de usuário na API do backend

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#120]
-Um ataque malicioso poderia alterar informações de outros usuários

Possível solução:
Implementar um controle de acesso a informações de usuários

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Todas as rotas do backend passam por processo de autenticação por default.
![image](https://user-images.githubusercontent.com/61878987/103487357-86d5b700-4de3-11eb-997b-363d16db5e80.png)
