### ISSUE TITLE
[Segurança]: Não há verificação de login de usuário para criação de notas

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#121]
-Um usuário que não deveria ter acesso à funcionalidade, poderia acessá-la

Possível solução:
Implementar controle de acesso e redirecionamento para home das funcionalidades relacionadas à nota

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Resolvido na #122 .
