### ISSUE TITLE
[Segurança]: Não há verificação de tentativa de acesso de páginas reservadas por meio de URL

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#122]
-Um usuário que não deveria ter acesso a alguma funcionalidade, página de conta de usuário ou outras informações sigilosas poderia acessá-las

Possível solução:
Implementar controle de acesso e redirecionamento para página de erro ao tentar acessar página que não deveria ter acesso

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Controle de acesso realizado.
![image](https://user-images.githubusercontent.com/61878987/103487321-36f6f000-4de3-11eb-9bcf-7585fdef165b.png)
