### ISSUE TITLE
[Segurança]: vulnerabilidades conhecidas do CORS

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#123]
-CORS tem uma série de vulnerabilidades, especialmente usando versões anteriores do Chrome como 84.0.4147.89, 80.0.3987.87 e outras mais, possibilitando vazamento de informações sensíveis de clientes

Possível solução:
Impedir uso de versões antigas do Chrome, manter a dependência atualizada

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações
