### ISSUE TITLE
[Segurança]: vulnerabilidades conhecidas do React

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#124]
-Aplicações em React versão 16.3.x tem problemas de escapamento de atributos informados pelo usuário em tempo de renderização, podendo gerar vulnerabilidade

Possível solução:
Atualizar versão do React, para 16.3.3 ou 16.4.2

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações
