### ISSUE TITLE
[Segurança]: Não há ferramenta para atualização constante das dependências instaladas

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#125]
Possível solução:
Instalar um plugin que faça essa atualização das dependências do projeto

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
O próprio node já possibilita a manutenção das dependências através do script [npm update](https://docs.npmjs.com/cli/v6/commands/npm-update).
