### ISSUE TITLE
[Segurança]: refactor de código desnecessário

### ISSUE THREAD

**Issue by RicardoBucard** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#126]
-Possíveis dependências não usadas e features, componentes, arquivos etc. não necessários ou que podem passar por refactor

Possível solução:
Criar um processo cíclico de checagem de código para encontrar possíveis ocorrências

**Comment by CordeiroAboumrad** [comment]
@cassiofb-dev checar com a equipe de Arquitetura os atendimentos às especificações

**Comment by cassiofb-dev** [comment]
Não necessário pois o projeto não passará por deploy.
