### ISSUE TITLE
Atualizar documento de especificação [2h]

### ISSUE THREAD

**Issue by jorge-g99** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#16]
:mag: / :heavy_exclamation_mark: É necessário atualizar e alinhar a documentação presente neste artefato, tendo em vista que foi ajustado todo o protótipo, por favor ajustar com urgência

Artefato:
[Link para tela de Testes de Aceitação](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Especifica%C3%A7%C3%A3o-dos-Testes-de-Aceita%C3%A7%C3%A3o)

**Comment by PedroAlpis** [comment]
A espeficação de testes de aceitação já foi ajustada para a iteração dessa semana. Estavamos na semana passada com 27 testes, e agora estamos em 39, ainda podendo é claro ocorrerem mais ajustes.
