### ISSUE TITLE
Salvar cidades (Dashboard) [2h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#21]
No Dashboard, o acionamento do botão "Salvar cidades" deverá persistir todas as cidades e suas informações, caso o usuário esteja logado.

Observação: Caso o usuário não esteja logado, ele deverá ser alertado de que, para salvar os dados, precisa ter uma conta.

O id será "saveAllCitiesButton".

Artefatos - Evidência em vídeo de Teste:
https://drive.google.com/drive/u/4/folders/1EahOkC5lnZ7utJYlwPD8J9osm71OY6GA

**Comment by cassiofb-dev** [comment]
Por causa de mudanças necessárias do trabalho esse botão foi retirado
