### ISSUE TITLE
Frontend da Tela de Busca de cidade (AdicionarCidade) [2h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#22]
Adicionar componente de busca (frontend).

- [x] Input de busca de cidade 
- [x] Botão de busca
- [x] Botões para cada resultado correspondente

Artefatos - Evidência em vídeo de Teste:
https://drive.google.com/drive/u/4/folders/1EahOkC5lnZ7utJYlwPD8J9osm71OY6GA

**Comment by gabrieldevsouza** [comment]
### BUG
Caixa de input de texto de busca não impede a inserção de caracteres inválidos, nem retorna nenhuma mensagem de erro para o usuário.
