### ISSUE TITLE
Backend da Tela de Busca de cidade (AdicionarCidade) [3h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#23]
Inserção da camada de backend para a tela AdicionarCidade.

Artefatos - Evidência em vídeo de Teste:
https://drive.google.com/drive/u/4/folders/1EahOkC5lnZ7utJYlwPD8J9osm71OY6GA

**Comment by DevGabrielDeSouza** [comment]
### BUG
Quando uma nova cidade é adicionada ao Dashboard e a aplicação retorna para esta tela, então nenhuma cidade é exibidad na tela de dashboard. No invés disso o texto _"Carregando cidades..."_ fica sendo exibido.
