### ISSUE TITLE
Edição de nota (NotaCidade) [4h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#30]
- [x] A nota, ao ser acionado, deverá passar de view mode para edit mode.

- [x] Um input deverá ser exibido para o usuário editar a nota. O id deverá ser "editCityNoteButton"

Artefatos - Evidência em vídeo de Teste:
https://drive.google.com/drive/u/4/folders/1EahOkC5lnZ7utJYlwPD8J9osm71OY6GA

**Comment by DevGabrielDeSouza** [comment]
### BUG
Deletar nota não abre uma caixa de confirmação para dar chance do usuário cancelar a ação.

**Comment by gabrieldevsouza** [comment]
### BUG
É possível adicionar notas com mais de 2048 caracteres.
