### ISSUE TITLE
Deletar nota (NotaCidade) [2h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#31]
- [x] Botão para excluir nota da cidade

- [x] Caso o usuário confirme a exclusão, a nota deverá ser deletada

Artefatos - Evidência em vídeo de Teste:
https://drive.google.com/drive/u/4/folders/1EahOkC5lnZ7utJYlwPD8J9osm71OY6GA

**Comment by gabrieldevsouza** [comment]
### BUG
Deletar nota não abre uma caixa de confirmação para dar chance do usuário cancelar a ação.
