### ISSUE TITLE
[PROBLEMA] Revisar modificações de PSW [2h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#4]
⚠️ :mag: / :heavy_exclamation_mark:   Revisar se modificações de PSW produzem novos casos de teste (caso surjam novas funcionalidades).

**Comment by gabrieldevsouza** [comment]
⚠️ **ISSUE INCOMPLETA**
@CordeiroAboumrad , @cassiofb-dev , @allan8991 favor revisar está Issue pois não há artefatos indicados para serem revisados nela.
Favor checar se ela não se tornou redundante após a criação de outras Issues específicas.
