### ISSUE TITLE
Criação do Burndown chart [1h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#41]
Criação do burndown chart no Google Sheets.

**Comment by Bernardo-Nascimento** [comment]
![BurnDown sem testes](https://user-images.githubusercontent.com/73723830/100643580-02da6c00-3319-11eb-8e2a-aebb1ac65e7d.png)
![BurnDown considerando testes](https://user-images.githubusercontent.com/73723830/100643584-03730280-3319-11eb-832c-a0c4229833b0.png)

**Comment by Bernardo-Nascimento** [comment]
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Burndown

**Comment by Bernardo-Nascimento** [comment]
![BurnDown sem testes](https://user-images.githubusercontent.com/73723830/100670247-5e1e5580-333d-11eb-88f9-39c8633a71fe.png)
![BurnDown considerando testes](https://user-images.githubusercontent.com/73723830/100670250-5f4f8280-333d-11eb-91f3-f7616b68373b.png)

**Comment by Bernardo-Nascimento** [comment]
![BurnDown sem testes](https://user-images.githubusercontent.com/73723830/100670494-b3f2fd80-333d-11eb-8560-02a151b41636.png)
![BurnDown considerando testes](https://user-images.githubusercontent.com/73723830/100670495-b48b9400-333d-11eb-9395-7438699ac0af.png)
