### ISSUE TITLE
Definir o domínio dos campos [1h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#5]
⚠️/ :computer: / :lock: Definição de faixas de valores válidos e inválidos.

Artefatos:
[Link pra tela 2 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-02---criarnovaconta)

[Link para tela 4 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-04---entrar)

[Link para tela 5 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-05---conta)

[Link para tela 7 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-07---adicionarcidade)

[Link para tela 10 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-10---notacidade)

**Comment by jorge-g99** [comment]
[Link pra tela 2 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-02---criarnovaconta)

[Link para tela 4 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-04---entrar)

[Link para tela 5 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-05---conta)

[Link para tela 7 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-07---adicionarcidade)

[Link para tela 10 - PSW](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#tela-10---notacidade)

**Comment by gabrieldevsouza** [comment]
:warning: **ISSUE REPROVADA POR TESTE**
Motivos:

- [ ] Documentação do sistema de notas não confere com especificação pedida pelo Diogo. Diogo exigiu no mínimo 4 campos:
 - O campo de texto está ok.
 - O campo de data parece estar ok, porém é interessante conferir se segue o que o Diogo pediu.
 - O campo numérico está **totalmente ausente** e é um dos requisitos mínimos da feature segundo o Diogo.
 - O campo de seleção está ausente ou não ficou claro na especificação. Favor esclarecê-lo caso exista, ou adicioná-lo.

@cassiofb-dev favor verificar com urgência.
