### ISSUE TITLE
Definir os perfis de acesso e variações nos protótipos [2h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#6]
:computer: / :lock: A equipe deverá realizar as seguintes tarefas:
- [x] Fazer a Matriz Perfil x Funcionalidade
- [x] Verificar existência de variações na exibição da tela

Artefato:
[Link do artefato Matriz Perfil x Funcionalidade](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#matriz-perfil)

**Comment by jorge-g99** [comment]
[Link do artefato Matriz Perfil x Funcionalidade](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/wiki/Prot%C3%B3tipo#matriz-perfil)

**Comment by RicardoBucard** [comment]
**ISSUE REPROVADA POR TESTE**

Motivos:

- [ ] Trocar salvar nota por editar nota no quadro CRUD

- Existem duas formas diferentes de criar uma nova conta, sendo uma na tela de login, que seria aconselhável retirar, por redundância

- Salvar uma cidade não é uma edição de dados sobre uma cidade, somente da lista de cidades. Para ter uma funcionalidade de Update sobre cidades poderia ser uma edição de dados que o usuário quer ou não ter acesso no dashboard principal. Exemplo: trocar mostrar temperatura para mostrar somente se está chovendo ou fazendo sol, trocar de Celsius para Fahrenheit.

- Não acho que faz sentido existir adicionar cidade e salvar cidade. As duas fazem a mesma coisa: adiciona uma cidade nova à lista de cidades que o usuário vai ter acesso. Seria mais simples para programar até se, caso o usuário esteja logado, essa informação já é salva no BD e, caso contrário, ela se perde com o fim da sessão.

- Os outros pontos sobre verificação de acesso parecem estar de acordo com a documentação apresentada
