### ISSUE TITLE
Estudar a linguagem Gherkin [2h p/ cada membro]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#8]
:mag: / :heavy_exclamation_mark: Aprender como criar casos de teste na linguagem

- [x] Estudo do @DevGabrielDeSouza 
- [x] Estudo do @PedroAlpis 
- [x] Estudo do @RicardoBucard

**Comment by gabrieldevsouza** [comment]
Preciso revisar com o @diogosmendonca sobre o _funcionamento, descrição e posicionamento no documento de múltiplos **Backgrounds**_ em diferentes cenários que utilizem combinações de Backgrounds.

Exemplo:

- Cadastrar Background A, B, C
- Um cenário utiliza Background B
- Um cenário utiliza Background B e C
- Um cenário utiliza Background A
- Um cenário utiliza Background A e C
- Um cenário utiliza background A e B e C
