### ISSUE TITLE
[BLOQUEADA] Passar os casos de teste para a linguagem Gherkin[6h]

### ISSUE THREAD

**Issue by CordeiroAboumrad** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2#9]
:mag: / :heavy_exclamation_mark: 
- [x] Criar os arquivos .feature necessários

**Comment by PedroAlpis** [comment]
Arquivos .features já foram **criados** e integrados no [Link para pasta do repositório](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-2/tree/main/frontend/cypress/integration)!
